// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmazbmfvwqqnjunvsbtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndtYXpibWZ2d3Fxbmp1bnZzYnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzEwNjksImV4cCI6MjA2MDMwNzA2OX0.21rAcFGt_g8Xy6rZgKyOLwmsMyiNpOevqWO_6wscwCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);